### ISSUE TITLE
NPE when mousing over the Philing cabinet

### ISSUE THREAD

**Issue by dragonpaw** [bafomdad/realfilingcabinet#37]
After breaking a Philing Cabinet my game crashes any time I mouse over it in my inventory.

```

java.lang.NullPointerException: Rendering screen
	at com.bafomdad.realfilingcabinet.blocks.ItemBlockAC.listAspects(ItemBlockAC.java:50)
	at com.bafomdad.realfilingcabinet.blocks.ItemBlockAC.func_77624_a(ItemBlockAC.java:35)
at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
```

https://gist.github.com/dragonpaw/53edcb98939effd693fa43966c9a7077

**Comment by bafomdad** [comment]
hm, it would seem like an oopsie with assuming that TC's aspects wouldn't be null during this part, and also a problem with checking if an itemstack isn't null instead of checking isEmpty.

I will fix this!
