### ISSUE TITLE
Client Crash when placing cabinet while looking up/down

### ISSUE THREAD

**Issue by codewarrior0** [bafomdad/realfilingcabinet#6]
`realfilingcabinet-1.10.2-0.5.9.jar`

```
06:03:11] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block realfilingcabinet:modelcabinet, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:222) ~[art$a.class:?]
    at com.bafomdad.realfilingcabinet.blocks.BlockRFC.func_180633_a(BlockRFC.java:111) ~[BlockRFC.class:?]
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:171) ~[acl.class:?]
```

Not surprising, since the FACING state on the cabinet is BlockHorizontal, while `EnumFacing.getFacingFromVector` may return Up or Down.

**Comment by bafomdad** [comment]
oh, whoops. Yeah, that's my bad.

It'll be fixed in the next update. Thanks for the report!
